version: '3'
services:
  datadog:
    image: datadog/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - ./dd-data/datadog-agent/run:/opt/datadog-agent/run:rw
    env_file:
      - ./.agent.env
    environment:
      - DD_APM_ENABLED=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_AC_INCLUDE="image:dd-test_example_1" # Use the image docker-compose creates
      - DD_AC_EXCLUDE="image:* name:datadog service:agent"
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
  example:
    build:
      context: ./
      dockerfile: Dockerfile
    command: yarn run dev
    env_file:
      - ./.env
    ports:
      - 3000:3000
    labels:
      com.datadoghq.ad.logs: '[{"source": "winston", "service": "dd-test"}]'
    volumes:
      - ${PWD}/index.js:/app/index.js
      - ${PWD}/package.json:/app/package.json
      - ${PWD}/yarn.lock:/app/yarn.lock
