version: '3'
services:
  datadog:
    image: datadog/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - ./dd-data/datadog-agent/run:/opt/datadog-agent/run:rw
    env_file:
      - ./.agent.env
  example:
    build:
      context: ./
      dockerfile: Dockerfile
    command: yarn run dev
    env_file:
      - ./.env
    ports:
      - 3000:3000
    volumes:
      - ./:/app